<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
	"http://www.w3.org/TR/1998/REC-html40-19980424/loose.dtd">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta name="generator" content="ABBYY FineReader PDF 15">
<style type="text/css">
 table.main {}
 tr.row {}
 td.cell {}
 div.block {}
 div.paragraph {}
 .font0 { font:7pt Arial, sans-serif; }
 .font1 { font:8pt Arial, sans-serif; }
 .font2 { font:9pt Arial, sans-serif; }
 .font3 { font:10pt Arial, sans-serif; }
 .font4 { font:12pt Arial, sans-serif; }
 .font5 { font:14pt Arial, sans-serif; }
 .font6 { font:8pt SimHei, sans-serif; }
 .font7 { font:10pt SimHei, sans-serif; }
 .font8 { font:12pt SimHei, sans-serif; }
 .font9 { font:14pt SimHei, sans-serif; }
 .font10 { font:9pt SimSun, serif; }
 .font11 { font:10pt SimSun, serif; }
 .font12 { font:10pt Times New Roman, serif; }

</style>
</head>
<body>
<p><span class="font3">172</span></p>
<p><span class="font11">第</span><span class="font3">10</span><span class="font11">章文件和异常</span></p>
<p><span class="font8">动手试一试</span></p>
<p><span class="font2">10-3</span><span class="font7">访客：</span><span class="font11">编写一个程序，提示用户输入其名字；用户作出响应后，将其名字写 入到文件</span><span class="font12">guest.txt</span><span class="font11">中°</span></p>
<p><span class="font2">104</span><span class="font7">访客</span><span class="font11">名单：编写一个</span><span class="font12">while</span><span class="font11">循环，提示用户输入其名字。用户输入其名字后， 在屏幕上打印一句问候语，并将一条访问记录添加到文件</span><span class="font12">guest_book.txt</span><span class="font11">中。确保这个 文件中的每条记录都独占一行。</span></p>
<p><span class="font2">10-5</span><span class="font7">关于编程的调查：</span><span class="font11">编写一个</span><span class="font12">while</span><span class="font11">循环，询问用户为何喜欢编程。每当用户输 入一个原因后，都将其添加到一个存储所有原因的文件中。</span></p>
<ul style="list-style:none;"><li>
<p><span class="font5">10.3</span><span class="font9"> 异常</span></p></li></ul>
<p><span class="font12">Python</span><span class="font11">使用被称为异常的特殊对象来管理程序执行期间发生的错误。每当发生让</span><span class="font12">Python</span><span class="font11">不知 所措的错误时，它都会创建一个异常对象。如果你编写了处理该异常的代码，程序将继续运行； 如果你未对异常进行处理，程序将停止，并显示一个</span><span class="font12">traceback,</span><span class="font11">其中包含有关异常的报告。</span></p>
<p><span class="font11">异常是使用</span><span class="font12">try-except</span><span class="font11">代码块处理的。</span><span class="font12">try-except</span><span class="font11">代码块让</span><span class="font12">Python</span><span class="font11">执行指定的操作，同时告 诉</span><span class="font12">Python</span><span class="font11">发生异常时怎么办。使用了</span><span class="font12">try-except</span><span class="font11">代码块时，即便出现异常，程序也将继续运行： 显示你编写的友好的错误消息，而不是令用户迷惑的</span><span class="font12">traceback</span><span class="font11">。</span></p>
<ul style="list-style:none;"><li><a name="caption1"></a>
<h5><a name="bookmark0"></a><span class="font4"><a name="bookmark1"></a>10.3.1</span><span class="font8"> 处理 </span><span class="font4">ZeroDivisionError </span><span class="font8">异常</span></h5></li></ul>
<p><span class="font11">下面来看一种导致</span><span class="font12">Python</span><span class="font11">引发异常的简单错误。你可能知道不能将一个数字除以</span><span class="font12">0,</span><span class="font11">但我们 还是让</span><span class="font12">Python</span><span class="font11">这样做吧：</span></p>
<p><span class="font3">division.py</span></p>
<p><span class="font0" style="font-weight:bold;">print</span><span class="font10" style="font-weight:bold;">(</span><span class="font0" style="font-weight:bold;">5/0</span><span class="font10" style="font-weight:bold;">)</span></p>
<p><span class="font11">显然，</span><span class="font12">Python</span><span class="font11">无法这样做，因此你将看到一个</span><span class="font12">traceback</span><span class="font11">：</span></p>
<p><span class="font0" style="font-weight:bold;">Traceback (most recent call last):</span></p>
<p><span class="font0" style="font-weight:bold;">File &quot;division.py&quot;, line 1, in &lt;modulo print</span><span class="font10" style="font-weight:bold;">(</span><span class="font0" style="font-weight:bold;">5/0</span><span class="font10" style="font-weight:bold;">)</span></p>
<p><span class="font10" style="font-weight:bold;">❶</span><span class="font0" style="font-weight:bold;"> ZeroDivisionError: division by zero</span></p>
<p><span class="font11">在上述</span><span class="font12">traceback</span><span class="font11">中，❶处指出的错误</span><span class="font12">ZeroDivisionError</span><span class="font11">是一个异常对象。</span><span class="font12">Python</span><span class="font11">无法按你的 要求做时，就会创建这种对象。在这种情况下，</span><span class="font12">Python</span><span class="font11">将停止运行程序，并指出引发了哪种异常, 而我们可根据这些信息对程序进行修改。下面我们将告诉</span><span class="font12">Python,</span><span class="font11">发生这种错误时怎么办；这样， 如果再次发生这样的错误，我们就有备无患了。</span></p>
<p><span class="font6">图灵社区会员江子涛</span><span class="font1">Tesla(jiangzitao201314@foxmail.com)</span><span class="font6">专享尊重版权</span></p>
</body>
</html>